sudo: true
language: java
jdk: openjdk8
notifications:
  email: false
  slack:
    rooms:
      secure: taYfHvkkrx/6FbL2FURMvYuu2vUB9thEK2qIo4DZPOzlwdn5XpqzAFmMXD1kCqDLTPGnhsGknbqkx+zMWIjLg3RCsxNm+yPik98QO9NCMu9L+gjEmxt31m/WGfYyCQ0Gf1/cxvxtrC/TK5T1GzF6XKsRExmDctOexwWJIBnFLP77LbWhKKe3F8DAWtzs8NwEsNGgovbhnqT3RMcymfmdWYyel2cheev79+G1EX0tPar76cAb3fBBHIi+TDeek5BEhcofoFFyBJDFQhTVZ/rImhCT8ilNAA9Eq5JWc2MY9UdYBclIVsNPXmqc9XQyU9LcQu8HjfO/afgZvG727kJCOU0UpM3u8LWHx/TxUqXQ7hspR5V0FdDxe9bvARzyMDtmgjWUracG45E9uwtANYSpv4iC+LchAoF9/9ACDN13ubAYBlS6WB6NbwlH2OwVf4IAsu52WCOntT/lvECnDB7Lo01hEu8cd8D64So6ftmokdehfGdhzLf6Ngg0YzfD3nS1ULmwKz0ytHeSJRSbXUdP/1XoEbp1/RaJVMauEoRDh34GEORh5brsBZ5f66C/O4caiYbpgrRLUMGDxHqD5ujKg0U809KG9suJf26eoErjzUDHRsQOg/6PxvpCPZBmi34hAh39W17jiea/C0DLTFdMEaCj7dqfwihr+pr0dtZlox0=
    on_success: change
    on_failure: always
stages:
- name: build
  if: branch IN (develop, master, dev_package)
- name: dev_build
  if: branch = develop
- name: package_build
  if: branch IN (master, dev_package)
- name: test_package
  if: branch IN (dbusel/bug-EWC-196)

jobs:
  include:
  - stage: build
    if: type IN (pull_request)
  - stage: dev_build
    if: type IN (push)
    before_install:
    - sudo apt-get install sshpass
    script:
    - mvn clean install
    - sshpass -p $DEV_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP 
      "service comsat stop; rm -rf /usr/bin/comsatd_bckp.jar /usr/bin/comsat_bckp.jar; mv /usr/bin/comsatd.jar
      /usr/bin/comsatd_bckp.jar; mv /usr/bin/comsat.jar /usr/bin/comsat_bckp.jar"
    - sshpass -p $DEV_MACHINE_PASSWORD scp daemon/target/comsat-daemon-jar-with-dependencies.jar
      $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP:/usr/bin/comsatd.jar
    - sshpass -p $DEV_MACHINE_PASSWORD scp client/target/comsat-client-jar-with-dependencies.jar
      $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP:/usr/bin/comsat.jar
    - sshpass -p $DEV_MACHINE_PASSWORD ssh $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP
      "service comsat start"
  - stage: package_build
    if: type IN (push)
    before_install:
    - sudo apt-get install sshpass xml-twig-tools
    script:
    - if [ "$TRAVIS_BRANCH" == "dev_package" ]; then export DEV=-dev; fi
    - export VERSION=`xml_grep --cond='project/version' pom.xml --text_only`
    - mvn clean install
    - sshpass -p $STAGE_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP "rm -rf /comsat-packaging-rpm/*; rm -rf /comsat-packaging/*;"
    - sshpass -p $STAGE_MACHINE_PASSWORD scp -o StrictHostKeyChecking=no -r comsat-packaging-rpm/*
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging-rpm/
    - sshpass -p $STAGE_MACHINE_PASSWORD scp -r comsat-packaging/*
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging/
    - sshpass -p $STAGE_MACHINE_PASSWORD scp client/target/comsat-client-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging/usr/bin/comsat.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp daemon/target/comsat-daemon-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging/usr/bin/comsatd.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp client/target/comsat-client-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging-rpm/usr/bin/comsat.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD scp daemon/target/comsat-daemon-jar-with-dependencies.jar
      $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP:/comsat-packaging-rpm/usr/bin/comsatd.jar
    - sshpass -p $STAGE_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP "cd /comsat-packaging; fpm -s dir -t deb -n \"comsat${DEV}\" -v $VERSION -a all --deb-no-default-config-files --after-install debian.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade debian.sh etc usr;
      package_cloud push iofog/comsat/ubuntu/precise comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/ubuntu/trusty comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/ubuntu/utopic comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/ubuntu/vivid comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/ubuntu/wily comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/ubuntu/xenial comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/debian/wheezy comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/debian/jessie comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/debian/stretch comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/debian/buster comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/raspbian/wheezy comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/raspbian/jessie comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/raspbian/stretch comsat${DEV}_${VERSION}_all.deb; 
      package_cloud push iofog/comsat/raspbian/buster comsat${DEV}_${VERSION}_all.deb; 
      cd /comsat-packaging-rpm; fpm -s dir -t rpm -n \"comsat${DEV}\" -v $VERSION -a all --rpm-os 'linux' --after-install rpm.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade rpm.sh etc usr; 
      package_cloud push iofog/comsat/fedora/22 comsat${DEV}-${VERSION}-1.noarch.rpm; 
      package_cloud push iofog/comsat/fedora/23 comsat${DEV}-${VERSION}-1.noarch.rpm; 
      package_cloud push iofog/comsat/fedora/24 comsat${DEV}-${VERSION}-1.noarch.rpm;
      package_cloud push iofog/comsat/el/6 comsat${DEV}-${VERSION}-1.noarch.rpm;  
      package_cloud push iofog/comsat/el/7 comsat${DEV}-${VERSION}-1.noarch.rpm"
    #- if [ "$TRAVIS_BRANCH" == "dev_package" ]; then sshpass -p $PRE_PROD_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no
    #  $PRE_PROD_MACHINE_USERNAME@$PRE_PROD_MACHINE_IP "service comsat stop; apt-get install --only-upgrade comsat-dev -y; service comsat start"; 
    #  else sshpass -p $PROD_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no
    #  $PROD_MACHINE_USERNAME@$PROD_MACHINE_IP "service comsat stop; apt-get install --only-upgrade comsat -y; service comsat start"; fi
  - stage: package_build
    if: type IN (push)
    before_install:
    - sudo apt-get install sshpass xml-twig-tools
    script:
    - sshpass -p $STAGE_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no $STAGE_MACHINE_USERNAME@$STAGE_MACHINE_IP "cd /comsat-packaging;
      package_cloud push iofog/comsat/ubuntu/xenial comsat-test_2.0_all.deb;"
